// Landmark address lookup (embedded for reliable production use)
export const LANDMARK_ADDRESSES: Record<string, string> = {
  "Alexandra Headland Surf Club": "167 Alexandra Parade, Alexandra Headland QLD 4572",
  "Aussie World": "1 Downunder Drive, Palmview QLD 4553",
  "Australia Zoo": "1638 Steve Irwin Way, Beerwah QLD 4519",
  "Beerwah Golf Club": "24 Biondi Crescent, Beerwah QLD 4519",
  "Big Pineapple": "76 Nambour Connection Rd, Woombye QLD 4559",
  "Bond University": "14 University Drive, Robina QLD 4226",
  "Bribie Island Golf Club": "7 Links Court, Woorim QLD 4507",
  "Brisbane Botanic Gardens": "152 Mount Coot-tha Road, Mt Coot-tha QLD 4066",
  "Brisbane City Hall": "64 Adelaide Street, Brisbane City QLD 4000",
  "Brisbane Convention Centre": "Glenelg St, South Brisbane QLD 4101",
  "Brisbane Cruise Terminal": "1 Cruise Terminal Drive, Pinkenba QLD 4008",
  "Brisbane Entertainment Centre": "1 Melaleuca Drive, Boondall QLD 4034",
  "Brisbane Showgrounds": "600 Gregory Terrace, Bowen Hills QLD 4006",
  "Buderim Private Hospital": "12 Elsa Wilson Drive, Buderim QLD 4556",
  "Caloundra Golf Club": "1 Charles Woodward Drive, Caloundra QLD 4551",
  "Caloundra Private Hospital": "96 Beerburrum Street, Caloundra QLD 4551",
  "Caloundra RSL": "19 West Terrace, Caloundra QLD 4551",
  "Clios Conferences Montville": "246 Petrie Creek Road, Rosemount QLD 4560",
  "Coolangatta Airport": "1 Eastern Avenue, Bilinga QLD 4225",
  "Coolum Surf Club": "1775-1779 David Low Way, Coolum Beach QLD 4573",
  "Cotton Tree Park": "Cotton Tree Parade, Maroochydore QLD 4558",
  "Currumbin Wildlife Sanctuary": "28 Tomewin Street, Currumbin QLD 4223",
  "DFO Brisbane Airport": "18th Avenue, Brisbane Airport QLD 4008",
  "Dreamworld": "1 Dreamworld Pkwy, Coomera QLD 4209",
  "Eagle Street Pier": "45 Eagle Street, Brisbane City QLD 4000",
  "Eat Street Northshore": "221D MacArthur Ave, Hamilton QLD 4007",
  "Elysium Noosa Resort": "14-16 Hastings Street, Noosa Heads QLD 4567",
  "Eumarella Shores Noosa Lake Retreat": "251 Eumarella Road, Weyba Downs QLD 4562",
  "Eumundi Markets": "80 Memorial Drive, Eumundi QLD 4562",
  "Flaxton Gardens": "313 Flaxton Drive, Flaxton QLD 4560",
  "GOMA": "15 Stanley Place, South Brisbane QLD 4101",
  "Glass House Mountains Ecolodge": "198 Barrs Road, Glass House Mountains QLD 4518",
  "Gold Coast Airport": "Eastern Ave, Bilinga QLD 4225",
  "Gold Coast Convention Centre": "2684-2690 Gold Coast Hwy, Broadbeach QLD 4218",
  "Gold Coast University Hospital": "1 Hospital Boulevard, Southport QLD 4215",
  "Grand Central Toowoomba": "Dent St & Margaret St, Toowoomba City QLD 4350",
  "Griffith University Gold Coast": "1 Parklands Drive, Southport QLD 4215",
  "Griffith University Nathan": "170 Kessels Road, Nathan QLD 4111",
  "Griffith University South Bank": "226 Grey Street, South Brisbane QLD 4101",
  "Harbour Town Gold Coast": "147-189 Brisbane Road, Biggera Waters QLD 4216",
  "Hastings Street Noosa": "Hastings Street, Noosa Heads QLD 4567",
  "Headland Golf Club": "Golf Links Road, Buderim QLD 4556",
  "Hinterland Golf Club Buderim": "Golf Links Road, Buderim QLD 4556",
  "Horton Park Golf Club": "1 Golf Street, Maroochydore QLD 4558",
  "Howard Smith Wharves": "5 Boundary Street, Brisbane City QLD 4000",
  "Indooroopilly Shopping Centre": "322 Moggill Road, Indooroopilly QLD 4068",
  "Ipswich Hospital": "Chelmsford Avenue, Ipswich QLD 4305",
  "Kawana Shoppingworld": "119 Point Cartwright Drive, Buddina QLD 4575",
  "Kings Beach Caloundra": "Ormonde Terrace, Kings Beach QLD 4551",
  "Kondalilla Eco Resort": "61 Kondalilla Falls Road, Flaxton QLD 4560",
  "Kondalilla Falls": "69 Kondalilla Falls Rd, Montville QLD 4560",
  "Lake Kawana Community Centre": "114 Sportsmans Parade, Bokarina QLD 4575",
  "Lone Pine Koala Sanctuary": "708 Jesmond Road, Fig Tree Pocket QLD 4069",
  "Maleny Golf Club": "15 Porters Lane, North Maleny QLD 4552",
  "Maleny Manor": "894 Landsborough Maleny Rd, Maleny QLD 4552",
  "Mantra Mooloolaba Beach": "7 Venning St, Mooloolaba QLD 4557",
  "Mapleton Falls": "78 Mapleton Falls Rd, Mapleton QLD 4560",
  "Maroochy RSL": "105 Memorial Avenue, Maroochydore QLD 4558",
  "Maroochy River Golf Club": "374-514 David Low Way, Bli Bli QLD 4560",
  "Maroochydore Surf Club": "34-36 Alexandra Parade, Maroochydore QLD 4558",
  "Mary Cairncross Scenic Reserve": "148 Mountain View Road, Maleny QLD 4552",
  "Mater Hospital Brisbane": "Raymond Terrace, South Brisbane QLD 4101",
  "Metricon Stadium": "Nerang Broadbeach Road, Carrara QLD 4211",
  "Montville Country Cabins": "396 Western Avenue, Montville QLD 4560",
  "Montville Village": "168-170 Main Street, Montville QLD 4560",
  "Mooloolaba Esplanade": "Mooloolaba Esplanade, Mooloolaba QLD 4557",
  "Mooloolaba Surf Club": "The Esplanade, Mooloolaba QLD 4557",
  "Morayfield Shopping Centre": "171 Morayfield Road, Morayfield QLD 4506",
  "Mount Coolum Golf Club": "17 Lumeah Drive, Mount Coolum QLD 4573",
  "Mount Coot-tha Lookout": "1012 Sir Samuel Griffith Drive, Mount Coot-tha QLD 4066",
  "Movie World": "Entertainment Rd, Oxenford QLD 4210",
  "Nambour General Hospital": "Hospital Road, Nambour QLD 4560",
  "Nambour Golf Club": "1051 Nambour Connection Rd, Nambour QLD 4560",
  "Narrows Escape Rainforest Retreat": "78 Narrows Road, Montville QLD 4560",
  "Netanya Noosa Beachfront Resort": "71 Hastings Street, Noosa Heads QLD 4567",
  "Noosa Blue Resort": "16 Noosa Drive, Noosa Heads QLD 4567",
  "Noosa Boathouse": "194 Gympie Terrace, Noosaville QLD 4566",
  "Noosa Civic": "28 Eenie Creek Road, Noosaville QLD 4566",
  "Noosa Eco Retreat": "44 Pomona Connection Road, Pomona QLD 4568",
  "Noosa Golf Club": "46 Cooroy Noosa Road, Tewantin QLD 4565",
  "Noosa Junction": "Sunshine Beach Road, Noosa Heads QLD 4567",
  "Noosa Lakes Resort": "3 Hilton Terrace, Tewantin QLD 4565",
  "Noosa Main Beach": "69 Hastings Street, Noosa Heads QLD 4567",
  "Noosa Marina": "2 Parkyn Court, Tewantin QLD 4565",
  "Noosa National Park": "Park Road, Noosa Heads QLD 4567",
  "Noosa RSL": "1 Memorial Ave, Tewantin QLD 4565",
  "Noosa Springs Golf & Spa Resort": "Links Drive, Noosa Heads QLD 4567",
  "Noosa Springs Golf Club": "Links Drive, Noosa Heads QLD 4567",
  "Noosa Surf Club": "69 Hastings Street, Noosa Heads QLD 4567",
  "Noosa Valley Golf Club": "14 Valley Drive, Doonan QLD 4562",
  "Noosa Valley Manor B&B": "115 Wust Rd, Doonan QLD 4562",
  "Novotel Sunshine Coast Resort": "270 Ocean Drive, Twin Waters QLD 4564",
  "Oaks Seaforth Resort Alexandra Headland": "98-110 Alexandra Parade, Alexandra Headland QLD 4572",
  "Oceans Mooloolaba": "101-105 Mooloolaba Esplanade, Mooloolaba QLD 4557",
  "Orion Springfield Central": "1 Main Street, Springfield Central QLD 4300",
  "PA Hospital": "199 Ipswich Road, Woolloongabba QLD 4102",
  "Pacific Fair": "Hooker Boulevard, Broadbeach QLD 4218",
  "Palmer Coolum Resort": "1 Warran Road, Yaroomba QLD 4573",
  "Parkland": "1 Parkland Boulevard, Brisbane City QLD 4000",
  "Pelican Waters Golf Club": "2 The Springs Boulevard, Pelican Waters QLD 4551",
  "Peppers Noosa Resort & Villas": "33A Viewland Drive, Noosa Heads QLD 4567",
  "Peregian Beach Hotel": "221-229 David Low Way, Peregian Beach QLD 4573",
  "Peregian Golf Course": "95 Peregian Springs Drive, Peregian Springs QLD 4573",
  "Pier 33 Mooloolaba": "33-45 Parkyn Parade, Mooloolaba QLD 4557",
  "Portside Wharf": "39 Hercules Street, Hamilton QLD 4007",
  "Princess Alexandra Hospital": "199 Ipswich Road, Woolloongabba QLD 4102",
  "QPAC": "100 Grey Street, South Brisbane QLD 4101",
  "QUT Gardens Point": "2 George Street, Brisbane QLD 4000",
  "QUT Kelvin Grove": "Victoria Park Road, Kelvin Grove QLD 4059",
  "Queen Street Mall": "Queen Street, Brisbane City QLD 4000",
  "Queens Wharf": "33 William Street, Brisbane City QLD 4000",
  "Queensland Museum": "Corner of Grey and Melbourne Streets, South Brisbane QLD 4101",
  "RACV Noosa Resort": "94 Noosa Drive, Noosa Heads QLD 4567",
  "RBWH": "Cnr Butterfield St and Bowen Bridge Road, Herston QLD 4029",
  "Ramada Resort Marcoola": "923 David Low Way, Marcoola QLD 4564",
  "Redcliffe Hospital": "108-130 Anzac Avenue, Redcliffe QLD 4020",
  "Rickys Noosa": "2 Quamby Place, Noosa Heads QLD 4567",
  "Riverlink Shopping Centre": "Cnr Downs Street and The Terrace, North Ipswich QLD 4305",
  "Robina Town Centre": "19 Robina Town Centre Drive, Robina QLD 4226",
  "Roma Street Parkland": "1 Parkland Boulevard, Brisbane City QLD 4000",
  "Royal Brisbane Hospital": "Cnr Butterfield St and Bowen Bridge Rd, Herston QLD 4029",
  "Rumba Beach Resort Caloundra": "10 Leeding Terrace, Caloundra QLD 4551",
  "SEA LIFE Sunshine Coast": "Parkyn Parade, Mooloolaba QLD 4557",
  "Sea Pearl Resort Mooloolaba": "87 Mooloolaba Esplanade, Mooloolaba QLD 4557",
  "Sea World": "Seaworld Drive, Main Beach QLD 4217",
  "Seahaven Beachfront Resort Noosa": "15 Hastings Street, Noosa Heads QLD 4567",
  "Secrets on the Lake": "207 Narrows Road, Montville QLD 4560",
  "SkyPoint Observation Deck": "Level 77, 3003 Surfers Paradise Boulevard, Surfers Paradise QLD 4217",
  "Sofitel Noosa Pacific Resort": "14-16 Hastings Street, Noosa Heads QLD 4567",
  "South Bank": "Stanley Street Plaza, South Brisbane QLD 4101",
  "South Bank Parklands": "Little Stanley Street, South Brisbane QLD 4101",
  "South Pacific Resort Noosa": "179 Weyba Road, Noosaville QLD 4566",
  "Spicers Clovelly Estate": "68 Balmoral Road, Montville QLD 4560",
  "Spicers Tamarind Retreat": "88 Obi Lane South, Maleny QLD 4552",
  "Springbrook National Park": "Springbrook Road, Springbrook QLD 4213",
  "Star Casino Gold Coast": "1 Casino Drive, Broadbeach QLD 4218",
  "State Library Queensland": "Cultural Precinct, Stanley Place, South Brisbane QLD 4101",
  "Stockland Caloundra": "47 Bowman Road, Caloundra QLD 4551",
  "Sun Lagoon Resort Noosa": "1 Quamby Place, Noosa Heads QLD 4567",
  "Suncorp Stadium": "40 Castlemaine Street, Milton QLD 4064",
  "Sunshine Coast Airport": "Friendship Avenue, Marcoola QLD 4564",
  "Sunshine Coast Convention Centre": "270 Ocean Drive, Twin Waters QLD 4564",
  "Sunshine Coast University": "90 Sippy Downs Drive, Sippy Downs QLD 4556",
  "Sunshine Coast University Hospital": "6 Doherty Street, Birtinya QLD 4575",
  "Sunshine Plaza": "154-164 Horton Parade, Maroochydore QLD 4558",
  "Surfair Events Centre": "923 David Low Way, Marcoola QLD 4564",
  "Surfair Marcoola": "923 David Low Way, Marcoola QLD 4564",
  "Surfers Paradise Beach": "The Esplanade, Surfers Paradise QLD 4217",
  "Tanawha Valley Par 3": "31 Palm Creek Road, Tanawha QLD 4556",
  "Tewantin-Noosa Golf Club": "46 Cooroy Noosa Road, Tewantin QLD 4565",
  "The Gabba": "411 Vulture Street, Woolloongabba QLD 4102",
  "The Ginger Factory": "50 Pioneer Road, Yandina QLD 4561",
  "The J Noosa": "60 Noosa Drive, Noosa Heads QLD 4567",
  "The Wharf Mooloolaba": "123 Parkyn Parade, Mooloolaba QLD 4557",
  "Tiffanys Maleny": "409 Mountain View Road, Maleny QLD 4552",
  "Tingirana Noosa": "25 Hastings Street, Noosa Heads QLD 4567",
  "Toowoomba Hospital": "154 Pechey Street, South Toowoomba QLD 4350",
  "Treasury Casino": "130 William Street, Brisbane City QLD 4000",
  "Twin Waters Golf Club": "151 Ocean Drive, Twin Waters QLD 4564",
  "UQ St Lucia": "Sir Fred Schonell Drive, St Lucia QLD 4072",
  "USC Sunshine Coast": "90 Sippy Downs Drive, Sippy Downs QLD 4556",
  "USQ Ipswich": "11 Salisbury Road, Ipswich QLD 4305",
  "USQ Toowoomba": "487-535 West Street, Toowoomba QLD 4350",
  "University of Queensland": "Sir Fred Schonell Drive, St Lucia QLD 4067",
  "Venue 114 Bokarina": "114 Sportsmans Parade, Bokarina QLD 4575",
  "Weddings at Tiffanys": "409 Mountain View Road, Maleny QLD 4552",
  "Westfield Carindale": "1151 Creek Road, Carindale QLD 4152",
  "Westfield Chermside": "Cnr Gympie & Hamilton Rd, Chermside QLD 4032",
  "Westfield Garden City": "Cnr Logan & Kessels Rd, Upper Mt Gravatt QLD 4122",
  "Westfield North Lakes": "Cnr Anzac Ave & North Lakes Dr, North Lakes QLD 4509",
  "Wet'n'Wild": "Entertainment Rd, Oxenford QLD 4210",
  "WhiteWater World": "1 Dreamworld Parkway, Coomera QLD 4209",
};
